### ISSUE TITLE
history file permissions

### ISSUE THREAD

**Issue by ClaudeM** [arangodb/linenoise-ng#9]
Is it worth applying this fix from antirez/linenoise? The change forces the history file to have mode 600 so it remains private. See the patch here.

https://github.com/antirez/linenoise/commit/c894b9e59f02203dbe4e2be657572cf88c4230c3#diff-72af1757e65272a44fc4aa3b479e2f3b

It may be useful to consider other code changes introduced after the fork.

**Comment by fceller** [comment]
Also see https://github.com/arangodb/linenoise-ng/pull/4/files

**Comment by fceller** [comment]
Fixed in 8e09e9293d666741e79bb5ecb9942ca4e652944e
